// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	MessageWarpper
	MessageLoginRequest
	MessageLoginResponse
	MessageLogoutRequest
	MessageLogoutResponse
	MessageClientLogin
	MessageClientLogout
	MessageClientReceived
	MessageClientSend
	MessageOnlineClients
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// 通讯类型
type COMMUNICATION_TYPE int32

const (
	COMMUNICATION_TYPE_LoginRequest   COMMUNICATION_TYPE = 0
	COMMUNICATION_TYPE_LoginResponse  COMMUNICATION_TYPE = 1
	COMMUNICATION_TYPE_LogoutRequest  COMMUNICATION_TYPE = 2
	COMMUNICATION_TYPE_LogoutResponse COMMUNICATION_TYPE = 3
	COMMUNICATION_TYPE_ClientLogin    COMMUNICATION_TYPE = 4
	COMMUNICATION_TYPE_ClientLogout   COMMUNICATION_TYPE = 5
	COMMUNICATION_TYPE_ClientReceived COMMUNICATION_TYPE = 6
	COMMUNICATION_TYPE_ClientSend     COMMUNICATION_TYPE = 7
	COMMUNICATION_TYPE_OnlineClients  COMMUNICATION_TYPE = 8
)

var COMMUNICATION_TYPE_name = map[int32]string{
	0: "LoginRequest",
	1: "LoginResponse",
	2: "LogoutRequest",
	3: "LogoutResponse",
	4: "ClientLogin",
	5: "ClientLogout",
	6: "ClientReceived",
	7: "ClientSend",
	8: "OnlineClients",
}
var COMMUNICATION_TYPE_value = map[string]int32{
	"LoginRequest":   0,
	"LoginResponse":  1,
	"LogoutRequest":  2,
	"LogoutResponse": 3,
	"ClientLogin":    4,
	"ClientLogout":   5,
	"ClientReceived": 6,
	"ClientSend":     7,
	"OnlineClients":  8,
}

func (x COMMUNICATION_TYPE) String() string {
	return proto1.EnumName(COMMUNICATION_TYPE_name, int32(x))
}
func (COMMUNICATION_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 消息壳
type MessageWarpper struct {
	Type                  COMMUNICATION_TYPE     `protobuf:"varint,1,opt,name=Type,enum=proto.COMMUNICATION_TYPE" json:"Type,omitempty"`
	MessageLoginRequest   *MessageLoginRequest   `protobuf:"bytes,2,opt,name=MessageLoginRequest" json:"MessageLoginRequest,omitempty"`
	MessageLoginResponse  *MessageLoginResponse  `protobuf:"bytes,3,opt,name=MessageLoginResponse" json:"MessageLoginResponse,omitempty"`
	MessageLogoutRequest  *MessageLogoutRequest  `protobuf:"bytes,4,opt,name=MessageLogoutRequest" json:"MessageLogoutRequest,omitempty"`
	MessageLogoutResponse *MessageLogoutResponse `protobuf:"bytes,5,opt,name=MessageLogoutResponse" json:"MessageLogoutResponse,omitempty"`
	MessageClientLogin    *MessageClientLogin    `protobuf:"bytes,6,opt,name=MessageClientLogin" json:"MessageClientLogin,omitempty"`
	MessageClientLogout   *MessageClientLogout   `protobuf:"bytes,7,opt,name=MessageClientLogout" json:"MessageClientLogout,omitempty"`
	MessageClientReceived *MessageClientReceived `protobuf:"bytes,8,opt,name=MessageClientReceived" json:"MessageClientReceived,omitempty"`
	MessageClientSend     *MessageClientSend     `protobuf:"bytes,9,opt,name=MessageClientSend" json:"MessageClientSend,omitempty"`
	MessageOnlineClients  *MessageOnlineClients  `protobuf:"bytes,10,opt,name=MessageOnlineClients" json:"MessageOnlineClients,omitempty"`
}

func (m *MessageWarpper) Reset()                    { *m = MessageWarpper{} }
func (m *MessageWarpper) String() string            { return proto1.CompactTextString(m) }
func (*MessageWarpper) ProtoMessage()               {}
func (*MessageWarpper) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessageWarpper) GetType() COMMUNICATION_TYPE {
	if m != nil {
		return m.Type
	}
	return COMMUNICATION_TYPE_LoginRequest
}

func (m *MessageWarpper) GetMessageLoginRequest() *MessageLoginRequest {
	if m != nil {
		return m.MessageLoginRequest
	}
	return nil
}

func (m *MessageWarpper) GetMessageLoginResponse() *MessageLoginResponse {
	if m != nil {
		return m.MessageLoginResponse
	}
	return nil
}

func (m *MessageWarpper) GetMessageLogoutRequest() *MessageLogoutRequest {
	if m != nil {
		return m.MessageLogoutRequest
	}
	return nil
}

func (m *MessageWarpper) GetMessageLogoutResponse() *MessageLogoutResponse {
	if m != nil {
		return m.MessageLogoutResponse
	}
	return nil
}

func (m *MessageWarpper) GetMessageClientLogin() *MessageClientLogin {
	if m != nil {
		return m.MessageClientLogin
	}
	return nil
}

func (m *MessageWarpper) GetMessageClientLogout() *MessageClientLogout {
	if m != nil {
		return m.MessageClientLogout
	}
	return nil
}

func (m *MessageWarpper) GetMessageClientReceived() *MessageClientReceived {
	if m != nil {
		return m.MessageClientReceived
	}
	return nil
}

func (m *MessageWarpper) GetMessageClientSend() *MessageClientSend {
	if m != nil {
		return m.MessageClientSend
	}
	return nil
}

func (m *MessageWarpper) GetMessageOnlineClients() *MessageOnlineClients {
	if m != nil {
		return m.MessageOnlineClients
	}
	return nil
}

// 客户端登入请求
type MessageLoginRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
}

func (m *MessageLoginRequest) Reset()                    { *m = MessageLoginRequest{} }
func (m *MessageLoginRequest) String() string            { return proto1.CompactTextString(m) }
func (*MessageLoginRequest) ProtoMessage()               {}
func (*MessageLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MessageLoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 客户端登入响应
type MessageLoginResponse struct {
	Succeed bool  `protobuf:"varint,1,opt,name=Succeed" json:"Succeed,omitempty"`
	Id      int32 `protobuf:"varint,2,opt,name=Id" json:"Id,omitempty"`
}

func (m *MessageLoginResponse) Reset()                    { *m = MessageLoginResponse{} }
func (m *MessageLoginResponse) String() string            { return proto1.CompactTextString(m) }
func (*MessageLoginResponse) ProtoMessage()               {}
func (*MessageLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MessageLoginResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func (m *MessageLoginResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 客户端登出请求
type MessageLogoutRequest struct {
}

func (m *MessageLogoutRequest) Reset()                    { *m = MessageLogoutRequest{} }
func (m *MessageLogoutRequest) String() string            { return proto1.CompactTextString(m) }
func (*MessageLogoutRequest) ProtoMessage()               {}
func (*MessageLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 客户端登出响应
type MessageLogoutResponse struct {
	Succeed bool `protobuf:"varint,1,opt,name=Succeed" json:"Succeed,omitempty"`
}

func (m *MessageLogoutResponse) Reset()                    { *m = MessageLogoutResponse{} }
func (m *MessageLogoutResponse) String() string            { return proto1.CompactTextString(m) }
func (*MessageLogoutResponse) ProtoMessage()               {}
func (*MessageLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MessageLogoutResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

// 其他客户端登陆
type MessageClientLogin struct {
	Id   int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *MessageClientLogin) Reset()                    { *m = MessageClientLogin{} }
func (m *MessageClientLogin) String() string            { return proto1.CompactTextString(m) }
func (*MessageClientLogin) ProtoMessage()               {}
func (*MessageClientLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MessageClientLogin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageClientLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 其他客户端登出
type MessageClientLogout struct {
	Id   int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
}

func (m *MessageClientLogout) Reset()                    { *m = MessageClientLogout{} }
func (m *MessageClientLogout) String() string            { return proto1.CompactTextString(m) }
func (*MessageClientLogout) ProtoMessage()               {}
func (*MessageClientLogout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MessageClientLogout) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageClientLogout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 客户端接收消息
type MessageClientReceived struct {
	Id      int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=Content" json:"Content,omitempty"`
}

func (m *MessageClientReceived) Reset()                    { *m = MessageClientReceived{} }
func (m *MessageClientReceived) String() string            { return proto1.CompactTextString(m) }
func (*MessageClientReceived) ProtoMessage()               {}
func (*MessageClientReceived) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MessageClientReceived) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageClientReceived) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageClientReceived) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 客户端发送消息
type MessageClientSend struct {
	Content string `protobuf:"bytes,1,opt,name=Content" json:"Content,omitempty"`
}

func (m *MessageClientSend) Reset()                    { *m = MessageClientSend{} }
func (m *MessageClientSend) String() string            { return proto1.CompactTextString(m) }
func (*MessageClientSend) ProtoMessage()               {}
func (*MessageClientSend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MessageClientSend) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 当前在线客户端
type MessageOnlineClients struct {
	Ids   []int32  `protobuf:"varint,1,rep,packed,name=Ids" json:"Ids,omitempty"`
	Names []string `protobuf:"bytes,2,rep,name=Names" json:"Names,omitempty"`
}

func (m *MessageOnlineClients) Reset()                    { *m = MessageOnlineClients{} }
func (m *MessageOnlineClients) String() string            { return proto1.CompactTextString(m) }
func (*MessageOnlineClients) ProtoMessage()               {}
func (*MessageOnlineClients) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MessageOnlineClients) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *MessageOnlineClients) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto1.RegisterType((*MessageWarpper)(nil), "proto.MessageWarpper")
	proto1.RegisterType((*MessageLoginRequest)(nil), "proto.MessageLoginRequest")
	proto1.RegisterType((*MessageLoginResponse)(nil), "proto.MessageLoginResponse")
	proto1.RegisterType((*MessageLogoutRequest)(nil), "proto.MessageLogoutRequest")
	proto1.RegisterType((*MessageLogoutResponse)(nil), "proto.MessageLogoutResponse")
	proto1.RegisterType((*MessageClientLogin)(nil), "proto.MessageClientLogin")
	proto1.RegisterType((*MessageClientLogout)(nil), "proto.MessageClientLogout")
	proto1.RegisterType((*MessageClientReceived)(nil), "proto.MessageClientReceived")
	proto1.RegisterType((*MessageClientSend)(nil), "proto.MessageClientSend")
	proto1.RegisterType((*MessageOnlineClients)(nil), "proto.MessageOnlineClients")
	proto1.RegisterEnum("proto.COMMUNICATION_TYPE", COMMUNICATION_TYPE_name, COMMUNICATION_TYPE_value)
}

func init() { proto1.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x69, 0xd3, 0x8f, 0x3b, 0x16, 0xbc, 0xcb, 0x40, 0x1e, 0xf0, 0x50, 0xe5, 0xa9, 0x42,
	0xda, 0x24, 0xc6, 0x0b, 0xbc, 0xf0, 0xa1, 0x0a, 0xa4, 0x48, 0x6b, 0x8b, 0xee, 0x3a, 0x21, 0x9e,
	0x50, 0x69, 0xac, 0xa9, 0x62, 0x73, 0x42, 0x93, 0x22, 0xf1, 0x13, 0xf8, 0x4b, 0xfc, 0x3a, 0x64,
	0x27, 0x5d, 0xed, 0xed, 0x56, 0xda, 0x53, 0xe3, 0x7b, 0xcf, 0x39, 0xf6, 0xf5, 0x39, 0x2e, 0xec,
	0x5f, 0xab, 0xb2, 0x9c, 0x5f, 0xaa, 0x93, 0x62, 0x95, 0x57, 0x39, 0x46, 0xf6, 0x27, 0xf9, 0xdb,
	0x81, 0x78, 0x5c, 0x37, 0xbe, 0xce, 0x57, 0x45, 0xa1, 0x56, 0x78, 0x0c, 0xed, 0xd9, 0x9f, 0x42,
	0xc9, 0x60, 0x10, 0x0c, 0xe3, 0xd3, 0xa3, 0x1a, 0x7f, 0x32, 0x9a, 0x8e, 0xc7, 0x17, 0x93, 0x74,
	0xf4, 0x71, 0x96, 0x4e, 0x27, 0xdf, 0x67, 0xdf, 0xbe, 0x7c, 0x22, 0x0b, 0xc3, 0x33, 0x78, 0xdc,
	0x08, 0x9c, 0xe5, 0x97, 0x4b, 0x4d, 0xea, 0xd7, 0x5a, 0x95, 0x95, 0x0c, 0x07, 0xc1, 0x70, 0xef,
	0xf4, 0x59, 0xc3, 0x66, 0x10, 0xc4, 0xd1, 0x70, 0x0a, 0x87, 0x7e, 0xb9, 0x2c, 0x72, 0x5d, 0x2a,
	0xd9, 0xb2, 0x72, 0xcf, 0x59, 0xb9, 0x1a, 0x42, 0x2c, 0xd1, 0x17, 0xcc, 0xd7, 0xd5, 0xe6, 0x7c,
	0xed, 0x1d, 0x82, 0x5b, 0x08, 0xb1, 0x44, 0x24, 0x78, 0x72, 0xab, 0xde, 0x1c, 0x31, 0xb2, 0x8a,
	0x2f, 0x78, 0xc5, 0xe6, 0x8c, 0x3c, 0x15, 0x53, 0xc0, 0xa6, 0x31, 0xba, 0x5a, 0x2a, 0x5d, 0xd9,
	0x11, 0x64, 0xc7, 0x0a, 0x1e, 0xf9, 0x82, 0x0e, 0x80, 0x18, 0x92, 0x63, 0xc7, 0x4d, 0x35, 0x5f,
	0x57, 0xb2, 0xcb, 0xd9, 0xe1, 0x22, 0x88, 0xa3, 0x39, 0xc3, 0xd6, 0x65, 0x52, 0x0b, 0xb5, 0xfc,
	0xad, 0x32, 0xd9, 0xe3, 0x86, 0xf5, 0x31, 0xc4, 0x53, 0xf1, 0x33, 0x1c, 0x78, 0x8d, 0x73, 0xa5,
	0x33, 0xd9, 0xb7, 0x7a, 0x92, 0xd3, 0x33, 0x7d, 0xba, 0x4b, 0x71, 0x9c, 0x9d, 0xea, 0xab, 0xa5,
	0x6e, 0x5a, 0xa5, 0x04, 0xce, 0x59, 0x0f, 0x42, 0x2c, 0x31, 0x79, 0xcf, 0x26, 0x19, 0x11, 0xda,
	0x93, 0xf9, 0x75, 0xfd, 0x1e, 0xfa, 0x64, 0xbf, 0xf1, 0x10, 0xa2, 0x59, 0xfe, 0x53, 0x69, 0x1b,
	0xf3, 0x3e, 0xd5, 0x8b, 0xe4, 0x03, 0x1f, 0x5e, 0x94, 0xd0, 0x3d, 0x5f, 0x2f, 0x16, 0x4a, 0x65,
	0x56, 0xa4, 0x47, 0x9b, 0x25, 0xc6, 0x10, 0xa6, 0x99, 0x15, 0x89, 0x28, 0x4c, 0xb3, 0xe4, 0x29,
	0x9f, 0xd6, 0xe4, 0xd5, 0x8e, 0xd0, 0xed, 0x96, 0x4e, 0xde, 0x70, 0x99, 0x6a, 0x36, 0x0c, 0x36,
	0x1b, 0xde, 0x0c, 0x17, 0x6e, 0x87, 0x4b, 0xde, 0xb2, 0x11, 0xba, 0x17, 0xf5, 0x62, 0x47, 0x5e,
	0xee, 0x43, 0x36, 0xb3, 0x8c, 0x72, 0x5d, 0x29, 0x5d, 0xd9, 0xe7, 0xde, 0xa7, 0xcd, 0x32, 0x39,
	0x66, 0x22, 0xe3, 0xc2, 0x03, 0x1f, 0xfe, 0x8e, 0x4f, 0x06, 0x0a, 0x68, 0xa5, 0x59, 0x29, 0x83,
	0x41, 0x6b, 0x18, 0x91, 0xf9, 0x34, 0x3e, 0x9a, 0xad, 0x4b, 0x19, 0x0e, 0x5a, 0xc6, 0x47, 0xbb,
	0x78, 0xf9, 0x2f, 0x00, 0xbc, 0xfb, 0x7f, 0x87, 0x02, 0x1e, 0xba, 0xc1, 0x10, 0x0f, 0xf0, 0x00,
	0xf6, 0x3d, 0xa7, 0x45, 0xd0, 0x94, 0xb6, 0xd6, 0x89, 0x10, 0x11, 0x62, 0xdf, 0x35, 0xd1, 0xc2,
	0x47, 0xb0, 0xe7, 0xd8, 0x22, 0xda, 0x46, 0xdc, 0xbd, 0x6d, 0x11, 0x19, 0x9a, 0x7f, 0x89, 0xa2,
	0x83, 0x31, 0xc0, 0xf6, 0x06, 0x44, 0xd7, 0xec, 0xe6, 0x8d, 0x28, 0x7a, 0x3f, 0x3a, 0x36, 0xf7,
	0xaf, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x5a, 0x14, 0x34, 0xf0, 0x05, 0x00, 0x00,
}
